import type { Metadata } from "next";
import {
  LegalDocument,
  LegalLink,
  LegalList,
  LegalSection,
  LEGAL_ENTITY_NAME,
} from "@/components/sections/LegalDocument";
import { contactDefaults } from "@/config/site";
import { withLocale } from "@/i18n/paths";
import { getLocale } from "@/i18n/get-locale";
import { buildMetadata } from "@/lib/seo";

const LAST_UPDATED = "September 13, 2026";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();
  return buildMetadata({
    path: "/legal/cookies",
    title: `Cookies Policy — ${LEGAL_ENTITY_NAME}`,
    description: `What cookies this website uses and why.`,
    locale,
  });
}

/**
 * /legal/cookies — reflects the site's actual cookie usage as of the
 * last-updated date: no analytics/advertising cookies exist in the
 * codebase, only the strictly necessary admin-session cookie
 * (`mtc_admin_session`, set in src/lib/admin/auth.ts) used to gate the
 * staff-only /admin panel. Update this page if that ever changes.
 */
export default async function CookiesPolicyPage() {
  const locale = await getLocale();
  const privacyHref = withLocale("/legal/privacy", locale);

  return (
    <LegalDocument
      title="Cookies Policy"
      lastUpdated={LAST_UPDATED}
      intro={`This Cookies Policy explains what cookies are and which cookies ${LEGAL_ENTITY_NAME} uses on this website.`}
    >
      <LegalSection heading="1. What cookies are">
        <p>
          Cookies are small text files placed on your device by a website you visit. They can be
          used to make a website function, remember information about your visit, or recognize you
          across visits.
        </p>
      </LegalSection>

      <LegalSection heading="2. Cookies we use">
        <p>
          This website uses a very limited number of cookies. We do not use cookies for
          advertising, and this website does not run analytics or visitor-tracking scripts of any
          kind.
        </p>
      </LegalSection>

      <LegalSection heading="3. Necessary cookies">
        <p>We use one strictly necessary cookie:</p>
        <LegalList
          items={[
            <span key="admin-session">
              <strong className="font-medium text-ink">mtc_admin_session</strong> — used to keep
              our staff signed in to the password-protected administration panel used to manage
              website content and respond to contact form submissions. This cookie is only set
              when someone signs in at the admin login page; it is not set for visitors browsing
              the public website (home, work, services, journal, or contact pages).
            </span>,
          ]}
        />
        <p>Because this cookie is required for the administration panel to function, it cannot be disabled while using that part of the site.</p>
      </LegalSection>

      <LegalSection heading="4. Analytics or other non-essential cookies">
        <p>
          As of the date at the top of this page, this website does not use analytics cookies,
          advertising cookies, or any other non-essential tracking technology (for example, tools
          such as Google Analytics or Meta Pixel are not installed on this website). Should this
          change in the future, we will update this policy and, where required by law, request
          your consent before setting any such cookies.
        </p>
      </LegalSection>

      <LegalSection heading="5. Third-party cookies">
        <p>
          We use Resend, a third-party service, to deliver email notifications generated by our
          contact form (see our{" "}
          <LegalLink href={privacyHref}>Privacy Policy</LegalLink> for details). This processing
          happens on our server when you submit the form — it does not set any cookie in your
          browser. This website does not otherwise embed third-party scripts, widgets, or ads that
          would set third-party cookies.
        </p>
      </LegalSection>

      <LegalSection heading="6. How to control cookies">
        <p>
          Most browsers let you view, manage, and delete cookies through their settings. You can
          typically choose to block or remove cookies at any time via your browser&rsquo;s
          preferences or help documentation. Blocking the necessary admin-session cookie will
          prevent access to the administration panel, but will not affect your ability to browse
          the public website.
        </p>
      </LegalSection>

      <LegalSection heading="7. Changes to this policy">
        <p>
          We may update this Cookies Policy if the cookies or technologies used on this website
          change. The &ldquo;Last updated&rdquo; date at the top of this page reflects the most
          recent revision.
        </p>
      </LegalSection>

      <LegalSection heading="8. Contact us">
        <p>Questions about this Cookies Policy can be sent to:</p>
        <p>
          {LEGAL_ENTITY_NAME}
          <br />
          <LegalLink href={`mailto:${contactDefaults.email}`}>{contactDefaults.email}</LegalLink>
          <br />
          {contactDefaults.location}
        </p>
      </LegalSection>
    </LegalDocument>
  );
}
